import { useEffect } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";

// Google public STUN servers to enable WebRTC across different networks (not just local)
const iceServers = [
  {
    urls: [
      "stun:stun.l.google.com:19302",
      "stun:stun1.l.google.com:19302",
      "stun:stun2.l.google.com:19302",
      "stun:stun3.l.google.com:19302",
      "stun:stun4.l.google.com:19302",
    ],
  },
];

function App() {
  // peerConnection is now using public STUN servers for ICE candidate gathering across all networks
  let peerConnection = new RTCPeerConnection({ iceServers });
  let localStream;
  let remoteStream;

  let init = async () => {
    localStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false });
    remoteStream = new MediaStream();
    document.getElementById("user-1").srcObject = localStream;
    document.getElementById("user-2").srcObject = remoteStream;

    localStream.getTracks().forEach((track) => {
      peerConnection.addTrack(track, localStream);
    });

    peerConnection.ontrack = (event) => {
      event.streams[0].getTracks().forEach((track) => {
        remoteStream.addTrack(track);
      });
    };
  };

  // Helper to wait until all ICE candidates are gathered
  const waitForICEGatheringComplete = () => {
    return new Promise((resolve) => {
      if (peerConnection.iceGatheringState === "complete") {
        resolve();
      } else {
        const checkState = () => {
          if (peerConnection.iceGatheringState === "complete") {
            peerConnection.removeEventListener("icegatheringstatechange", checkState);
            resolve();
          }
        };
        peerConnection.addEventListener("icegatheringstatechange", checkState);
      }
    });
  };

  let createOffer = async () => {
    // clear textarea
    document.getElementById("offer-sdp").value = "";
    const offer = await peerConnection.createOffer();
    await peerConnection.setLocalDescription(offer);

    // Wait until ICE gathering is complete
    await waitForICEGatheringComplete();

    // output full offer SDP w/ ICE candidates
    document.getElementById("offer-sdp").value = JSON.stringify(peerConnection.localDescription);
  };

  let createAnswer = async () => {
    let offerStr = document.getElementById("offer-sdp").value;
    if (!offerStr) return;
    let offer = JSON.parse(offerStr);

    // clear textarea
    document.getElementById("answer-sdp").value = "";

    await peerConnection.setRemoteDescription(offer);

    let answer = await peerConnection.createAnswer();
    await peerConnection.setLocalDescription(answer);

    // Wait until ICE gathering is complete
    await waitForICEGatheringComplete();

    // output full answer SDP w/ ICE candidates
    document.getElementById("answer-sdp").value = JSON.stringify(peerConnection.localDescription);
  };

  let addAnswer = async () => {
    let answerStr = document.getElementById("answer-sdp").value;
    if (!answerStr) return;
    let answer = JSON.parse(answerStr);
    if (!peerConnection.currentRemoteDescription) {
      await peerConnection.setRemoteDescription(answer);
    }
  };

  useEffect(() => {
    init();
    document.getElementById("create-offer").addEventListener("click", createOffer);
    document.getElementById("create-answer").addEventListener("click", createAnswer);
    document.getElementById("add-answer").addEventListener("click", addAnswer);
    // eslint-disable-next-line
  }, []); // mount only ONCE for event binding

  return (
    <>
      <div id="intro-container">
        <h2>WebRTC Handshake - Passing SDP with no signaling</h2>

        <img width="100%" src="WebRTC SDP Gif.gif" />

        <p>
          <b>Instructions: </b>Start by opening two tabs (can be on different devices, networks, or
          WiFi) and follow the steps below to pass SDP offer and answer. This works cross-network by
          using public STUN servers.
        </p>
        <a href="https://github.com/dennisivy/WebRTC-Handshake/" target="_blank">
          <b>Source Code</b>
        </a>
      </div>

      <div id="videos">
        <video className="video-player" id="user-1" autoPlay playsInline></video>
        <video className="video-player" id="user-2" autoPlay playsInline></video>
      </div>

      <div className="step">
        <p>
          <strong>Step 1:</strong> User 1, click "Create offer" to generate SDP offer and copy offer
          from text area below.
        </p>
        <button id="create-offer">Create Offer</button>
      </div>

      <label>SDP OFFER:</label>
      <textarea id="offer-sdp" placeholder="User 2, paste SDP offer here..."></textarea>

      <div className="step">
        <p>
          <strong>Step 2:</strong> User 2, paste SDP offer generated by user 1 into text area above,
          then click "Create Answer" to generate SDP answer and copy the answer from the text area
          below.
        </p>
        <button id="create-answer">Create answer</button>
      </div>

      <label>SDP Answer:</label>
      <textarea id="answer-sdp" placeholder="User 1, paste SDP answer here..."></textarea>

      <div className="step">
        <p>
          <strong>Step 3:</strong> User 1, paste SDP offer generated by user 2 into text area above
          and then click "Add Answer"
        </p>
        <button id="add-answer">Add answer</button>
      </div>
      <div>
        <small>
          <b>Note:</b> This app now uses Google public STUN servers so you can connect outside your
          local network as well. In extreme network/firewall situations, a TURN server may be
          needed.
        </small>
      </div>
    </>
  );
}

export default App;
